<?php 
$this->title = "Meus Albums";
$this->headTitle($this->title);
?>

<p> <a href="<?php echo $this->url(array('controller'=>'index','action'=>'add')); ?>"> Adicionar Novo Album </a> </p>
<table>
	<tr>
		<tr>
			<th>Titulo</th>
			<th>Artista</th>
			<th>&nbsp</th>
		</tr>
	</tr>
	<?php foreach ($this->albums as $album) : ?>
	<tr>
		<td> <?php echo $this->escape($album->title); ?> </td>
		<td> <?php echo $this->escape($album->artist); ?> </td>
		<td> 
			<a href="<?php echo $this->url(array('controller'=>'index','action'=>'edit', 'id'=>$album->id));?>">Editar</a>
			<a href="<?php echo $this->url(array('controller'=>'index','action'=>'delete', 'id'=>$album->id));?>">Excluir</a>
		</td>
	</tr>
	<?php endforeach; ?>
</table>